<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Proceed_1</name>
   <tag></tag>
   <elementGuidId>e2811428-0d53-4f5f-b28e-2bb14874a89e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>footer.form-footer > button.button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>setupForm.$invalid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed
            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;whatinput-types-initial whatinput-types-mouse&quot;]/body[@class=&quot;ng-scope&quot;]/div[@class=&quot;default ng-scope&quot;]/div[@class=&quot;main-wrapper ng-scope&quot;]/main[@class=&quot;main&quot;]/section[@class=&quot;main-contents&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;content ng-scope&quot;]/div[@class=&quot;content ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/section[@class=&quot;content-box&quot;]/div[@class=&quot;eb-tabs ng-isolate-scope&quot;]/div[@class=&quot;steps ng-scope&quot;]/form[@class=&quot;regular-form ng-pristine ng-scope ng-valid ng-valid-required&quot;]/section[@class=&quot;step ng-isolate-scope done current&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;row expanded ng-scope&quot;]/footer[@class=&quot;form-footer&quot;]/button[@class=&quot;button&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum Transaction Per Day'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make sure you have accurately filled up the details'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please make sure you have all the right details for the customer'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
   </webElementXpaths>
</WebElementEntity>
