<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Number_mobile</name>
   <tag></tag>
   <elementGuidId>cc493dcd-8289-4ba3-a48d-82cf1de453bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;mobile&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='mobile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>corporateCreateCtrl.corporate.mobile</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobile</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^[9][0-9]{9}$/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>!corporateCreateCtrl.corporate.nonResident</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-invalid ng-valid-maxlength ng-not-empty ng-valid-required ng-invalid-pattern ng-dirty-add ng-valid-parse-add ng-valid-server-add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;whatinput-types-initial whatinput-types-mouse&quot;]/body[@class=&quot;ng-scope&quot;]/div[@class=&quot;default ng-scope&quot;]/div[@class=&quot;main-wrapper ng-scope&quot;]/main[@class=&quot;main&quot;]/section[@class=&quot;main-contents&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;content ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/section[@class=&quot;content-box&quot;]/div[@class=&quot;eb-tabs ng-isolate-scope&quot;]/div[@class=&quot;steps ng-scope&quot;]/form[@class=&quot;regular-form ng-pristine ng-scope ng-invalid ng-valid-minlength ng-valid-maxlength ng-valid-email ng-valid-required ng-invalid-pattern ng-dirty-add ng-valid-parse-add ng-valid-server-add ng-animate ng-pristine-remove&quot;]/section[@class=&quot;step ng-isolate-scope current&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;row ng-scope&quot;]/div[@class=&quot;column large-11 large-offset-1&quot;]/div[@class=&quot;row ng-scope&quot;]/div[@class=&quot;column large-6&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;ng-pristine ng-untouched ng-invalid ng-valid-maxlength ng-not-empty ng-valid-required ng-invalid-pattern ng-dirty-add ng-valid-parse-add ng-valid-server-add&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='mobile']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
